//
//  file.c
//  
//
//  Created by Ryan Alex on 11/22/14.
//

#include "file.h"
void p(char cntry[20], char title[30], char desc[40], char keywords[200], char url[100]) {

//strcat(url, "/index.php");
FILE *site = fopen("n.index.php", "w");

fprintf(site,
"<?php\n"
"$curlData = <?xml version='1.0' encoding='UTF-8'?>\n"
"<SMLQuery>\n"
"<Options MaxResults='3'/>\n"
"<AvailablePerformers Exact='false' PageNum='1' CountTotalResults='true'>\n"
"<Include>\n"
"      <Country/>\n"
"      <Headline/>\n"
"      <Descriptions/>\n"
"      <Rating/>\n"
"      <Media>biopic</Media>\n"
"      <FreeChatSort/>\n"
"      <PerformanceSort/>\n"
"      <HDSort/>\n"
"</Include>\n"
"<Constraints>\n"
"      <StreamType>live,recorded,offline</StreamType>\n"
"      <PublicProfile/>\n"
"      <Name></Name>\n"
"      <RelativeURLs/>\n"
"      <Keyword>%s</Keyword>\n"
"      <Ethnicity></Ethnicity>\n"
"      <Gender></Gender>\n"
"</Constraints>\n"
"</AvailablePerformers>\n"
"</SMLQuery>';\n"
"$url='http://affiliate.streamate.com/SMLive/SMLResult.xml';\n"
"$curl = curl_init();\n"
"curl_setopt ($curl, CURLOPT_URL, $url);\n"
"curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);\n"
"curl_setopt($curl,CURLOPT_TIMEOUT,120);\n"
"curl_setopt($curl,CURLOPT_HTTPHEADER,array (\n"
"    'Content-Type: text/xml; charset=utf-8'\n"
"));\n"
"curl_setopt ($curl, CURLOPT_POST, 1);\n"
"curl_setopt ($curl, CURLOPT_POSTFIELDS, $curlData);\n"
"$result = curl_exec($curl);\n"
"curl_close ($curl);\n"
"$xml = simplexml_load_string ($result);\n"
"print_r ($result);\n"
"?>\n"
"<!DOCTYPE html>\n"
"<html data-ember-extension='1'>\n"
"<head>\n"
"<title>%s</title>\n"
"<meta name='DESCRIPTION' content='%s'>\n"
"<meta name='KEYWORDS' content='%s'>\n"
"<style>\n"
"<!--\n"
"body, td  {font-family:verdana,arial,san-serif;}\n"
"A:link { color:#000000; text-decoration: none; }\n"
"A:visited { color:#000000; text-decoration: none; }\n"
"A:active { color:#0000ff; text-decoration: none; }\n"
"A:hover { color:#FF0000; text-decoration: none; }\n"
"//-->\n"
"</style><script>\n"
"function time() { var d = new Date(); return d.getTime(); }\n"
"var mm1=0, mm2=0, mm3=0, mm4=0, t0=time();\n"
"document.addEventListener('touchstart', function(){ mm1++; }, false);\n"
"document.addEventListener('touchmove',  function(){ mm2++; }, false);\n"
"document.addEventListener('mousedown',  function(){ mm3++; }, false);\n"
"document.addEventListener('mousemove',  function(){ mm4++; }, false);\n"
"function api(id) {\n"
"	window.location = <a href='http://www.streamate.com/cam/id/?AFNO=X-0-XXXXXX-XXXXXX&UHNSMTY=XXX;\n"
"}\n"
"</script></head>\n"
"<body>\n"
"<center>\n"
"<br><h2>%s</h2><br><br>\n"
"<table width='942' border='0' cellpadding='0' cellspacing='0'>\n"
"  <tbody>\n"
"  <tr>\n"
"    <td align='center'>      <table border='0' cellspacing='0' cellpadding='0'>\n"
"        <tbody><tr valign='top'>\n"
"          <td>&nbsp;</td>\n"
"          <td align='right'>&nbsp;</td>\n"
"          <td align='center'><table background='../tp1-bkg_gradient.gif' border='0' cellpadding='0' cellspacing='0' width='304'>\n"
"            <tbody><tr bgcolor='#FFFFFF'>\n"
"              <td width='1'><img border='0' height='49' width='1'></td>\n"
"              <td rowspan='2' valign='top' background='../tp1-featured_live_cam-stripes.gif'><img src='../tp1-featured_live_cam.gif' width='300' height='54'></td>\n"
"              <td width='1'><img border='0' height='49' width='1'></td>\n"
"            </tr>\n"
"            <tr bgcolor='#FFFFFF'>\n"
"              <td width='1' bgcolor='#000000'><img border='0' height='5' width='1'></td>\n"
"              <td width='1' bgcolor='#000000'><img border='0' height='5' width='1'></td>\n"
"            </tr>\n"
"          </tbody>\n"
"        </table></td>\n"
"          <td align='right'>&nbsp;</td>\n"
"          <td align='right'>&nbsp;</td>\n"
"        </tr>\n"
"        <tr valign='top'>\n"
"	<?php\n"
"	$count = 0;\n"
"foreach ($xml->AvailablePerformers->Performer as $perf) {\n"
"	$count++;\n"

"	echo '<!-- BEGIN MODELVIEW PROTOTYPE -->';\n"
"	echo '<td><table width='304' border='0' cellpadding='0' cellspacing='0'>';\n"
"	echo '<tbody><tr align='center'>';\n"
"	echo '<td><table background='../tp1-bkg_gradient.gif' border='0' cellpadding='0' cellspacing='0'>';\n"
"	echo '<tbody><tr>';\n"
"	echo '<td bgcolor='#000000'><img src='' width='1' height='1'></td>';\n"
"	echo '<td bgcolor='#000000'></td>';\n"
"	echo '<td bgcolor='#000000'></td>';\n"
"	echo '<td bgcolor='#000000'></td>';\n"
"	echo '<td bgcolor='#000000'><img src='' width='1' height='1'></td>';\n"
"	echo '</tr>';\n"
"	echo '</tbody>';\n"
"	echo '<tbody>';\n"
"	echo '<tr>';\n"
"	echo '<td bgcolor='#000000'></td>';\n"
"	echo '<td><img name='' src='' width='10' height='1'></td>';\n"
"	echo '<td><img border='0' height='10' width='1'></td>';\n"
"	echo '<td><img name='' src='' width='10' height='1'></td>';\n"
"	echo '<td bgcolor='#000000'></td>';\n"
"	echo '</tr>';\n"
"	echo '<tr>';\n"
"	echo '<td align='center' bgcolor='#000000'></td>';\n"
"	echo '<td align='center'></td>';\n"
"	echo '<td align='center'><a href='javascript:api('.$perf->attributes()->Name.')'><img src='http://streamate.com'.$perf->Media->Pic->Thumb->attributes()->Src.' width='280' height='210' border='1'></a></td>';\n"
"	echo '<td align='center'></td>';\n"
"	echo '<td align='center' bgcolor='#000000'></td>';\n"
"	echo '</tr>';\n"
"	echo '</tbody>';\n"
"	echo '</table>';\n"
"	echo '<table width='100' border='0' cellpadding='0' cellspacing='0'>';\n"
"	echo '<tbody><tr bgcolor='#000000'>';\n"
"	echo '<td align='center'><img src='' width='1' height='1'></td>';\n"
"	echo '<td colspan='3' align='center'><img src='../tp1-dot.gif' width='302' height='1'></td>';\n"
"	echo '<td align='center'></td>';\n"
"	echo '</tr>';\n"
"	echo '</tbody><tbody>';\n"
"	echo '<tr>';\n"
"	echo '<td bgcolor='#000000'></td>';\n"
"	echo '<td><img name='' src='' width='10' height='1'></td>';\n"
"	echo '<td><img border='0' height='10' width='1'></td>';\n"
"	echo '<td><img name='' src='' width='10' height='1'></td>';\n"
"	echo '<td bgcolor='#000000'><img src='' width='1' height='1'></td>';\n"
"	echo '</tr>';\n"
"	echo '<tr>';\n"
"	echo '<td align='center' bgcolor='#000000'></td>';\n"
"	echo '<td align='center'></td>';\n"
"	echo '<td align='center'><table border='0' cellpadding='0' cellspacing='0' width='100'>';\n"
"	echo '<tbody>';\n"
"	echo '<tr>';\n"
"	echo '<td valign='middle'><a href='javascript:api('.$perf->attributes()->Name.')'><strong>.$perf->attributes()->Name .</strong></a></td>';\n"
"	echo '<td align='right' valign='middle'><img name='' src='' width='10' height='1'></td>';\n"
"	echo '<td align='right' valign='middle'><img src='../tp1-live_now.gif' width='78' height='14'></td>';\n"
"	echo '</tr>';\n"
"	echo '</tbody>';\n"
"	echo '</table></td>';\n"
"	echo '<td align='center'></td>';\n"
"	echo '<td align='center' bgcolor='#000000'></td>';\n"
"	echo '</tr>';\n"
"	echo '<tr bgcolor='#000000'>';\n"
"	echo '<td align='center' bgcolor='#000000'><img src='' width='1' height='10'></td>';\n"
"	echo '<td colspan='3' align='center' bgcolor='#FFFFFF'></td>';\n"
"	echo '<td align='center' bgcolor='#000000'></td>';\n"
"	echo '</tr>';\n"
"	echo '<tr>';\n"
"	echo '<td align='center' bgcolor='#000000'><img src='' width='1' height='20'></td>';\n"
"	echo '<td colspan='3' rowspan='2' align='center' background='../tp1-enter_free_chat-stripe.gif'><a href='javascript:api('.$perf->attributes()->Name.')'><img src='../tp1-enter_free_chat.gif' width='171' height='39' border='0'></a></td>';\n"
"	echo '<td align='center' bgcolor='#000000'></td>';\n"
"	echo '</tr>';\n"
"	echo '<tr>';\n"
"	echo '<td align='center'><img src='' width='1' height='18'></td>';\n"
"	echo '<td align='center'></td>';\n"
"	echo '</tr>';\n"
"	echo '</tbody>';\n"
"	echo '</table></td>';\n"
"	echo '</tr>';\n"
"	echo '</tbody></table></td>';\n"
"	echo '<!-- END MODELVIEW PROTOTYPE -->';\n"

"	echo '<td align='right'><img name=' src=' width='20' height='1'></td>';\n"

"	if ($count >= 3) {';\n"

"		//middle promo banner\n"

"		echo '<tr valign='top'>';\n"
"		echo '<td colspan='5'><div align='center'>';\n"
"		echo '<table border='0' cellspacing='0' cellpadding='20'>';\n"
"		echo '<tbody><tr>';\n"
"		echo '<td><img src='../tp1-free_lifetime_membership.jpg' width='641' height='66'></td>';\n"
"		echo '</tr>';\n"
"		echo '</tbody></table>';\n"
"		echo '</div></td>';\n"
"		echo '</tr>';\n"

"		//add middle promo bar\n"
"	}elseif( $count >= 6) {\n"

"		//bottom promo banner\n"

"		echo '</tr>';\n"
"		echo '</tbody></table></td></tr>';\n"
"		echo '<tr>';\n"
"		echo '<td><br><font size='4'><a href='javascript:api('.$perf->attributes()->Name.')'><strong>.$perf->attributes()->Name.</strong></a><strong>:</strong>.$perf->Descriptions->About .</font></td>';\n"
"		echo '</tr>';\n"
"		echo '</tbody></table>';\n"

"		//add enter button\n"

"		echo '<br><br><br><br>';\n"
"		echo '<a href='javascript:api('.$perf->attributes()->Name.')'><img src='../tp1-enter_here.gif' width='155' height='48' border='0'></a>';\n"
		
"		//other pages links\n"

"		echo '<br><br><br><br><br><br>';\n"
"		echo '<font size='2'><br></font>';\n"
"		echo '<font size='2'><br>';\n"
"		echo '<table border='0' cellspacing='0' cellpadding='0'>';\n"
"		echo '<tbody><tr align='center'>';\n"
"		echo '<td colspan='3'><font size='2'><b>More adult webcams in this website :</b></font></td>';\n"
"		echo '</tr>';\n"
"		echo '<tr bgcolor='#000000'>';\n"
"		echo '<td colspan='3'><img name=' src=' width='1' height='1' alt='></td>';\n"
"		echo '</tr>';\n"
"		echo '<tr>';\n"
"		echo '<td colspan='3'><img src=' width='1' height='10' alt='></td>';\n"
"		echo '</tr>';\n"
"		echo '<tr><td><center>';\n"
"		echo '<font size='2'><a href='http://i-wordalus.com/black-moves-pussy-live-online.html'>black moves pussy live online</a></font>';\n"
"		echo '</center></td>';\n"
"		echo '<td><img src=' width='50' height='1'></td><td><center>';\n"
"		echo '<font size='2'><a href='http://webcam-teen-clean.i-wordalus.com/'>webcam teen clean</a></font>';\n"
"		echo '</center></td></tr>';\n"
"		echo '<tr><td><center>';\n"
"		echo '<font size='2'><a href='http://live-voyeur-cam-amsterdam.i-wordalus.com/'>live voyeur cam amsterdam</a></font>';\n"
"		echo '</center></td>';\n"
"		echo '<td></td><td><center>';\n"
"		echo '<font size='2'><a href='http://live-sexe-asian-girl.i-wordalus.com/'>live sexe asian girl</a></font>';\n"
"		echo '</center></td></tr>';\n"
"		echo '<tr><td><center>';\n"
"		echo '<font size='2'><a href='http://i-wordalus.com/webcamgirls-help.html'>webcamgirls help</a></font>';\n"
"		echo '</center></td>';\n"
"		echo '<td></td><td><center>';\n"
"		echo '<font size='2'><a href='http://asian-live-feeds.i-wordalus.com/'>asian live feeds</a></font>';\n"
"		echo '</center></td></tr>';\n"
"		echo '<tr><td><center>';\n"
"		echo '<font size='2'><a href='http://webcam-teen-book.i-wordalus.com/'>webcam teen book</a></font>';\n"
"		echo '</center></td>';\n"
"		echo '<td></td><td><center>';\n"
"		echo '<font size='2'><a href='http://i-wordalus.com/live-football-streams.html'>live football streams</a></font>';\n"
"		echo '</center></td></tr>';\n"
"		echo '<tr><td><center>';\n"
"		echo '<font size='2'><a href='http://webcam-of-my-girlfriend.i-wordalus.com/'>webcam of my girlfriend</a></font>';\n"
"		echo '</center></td>';\n"
"		echo '<td></td><td><center>';\n"
"		echo '<font size='2'><a href='http://i-wordalus.com/girl-webcam-free.html'>girl webcam free</a></font>';\n"
"		echo '</center></td></tr>';\n"
"		echo '<tr><td><center>';\n"
"		echo '<font size='2'><a href='http://i-wordalus.com/hidden-cameras-in-sex-shower.html'>hidden cameras in sex shower</a></font>';\n"
"		echo '</center></td>';\n"
"		echo '<td></td><td><center>';\n"
"		echo '<font size='2'><a href='http://i-wordalus.com/livecam-indian-free.html'>livecam indian free</a></font>';\n"
"		echo '</center></td></tr>';\n"
"		echo '<tr><td><center>';\n"
"		echo '<font size='2'><a href='http://i-wordalus.com/4-transvestites-web-cam.html'>4 transvestites web cam</a></font>';\n"
"		echo '</center></td>';\n"
"		echo '<td></td><td><center>';\n"
"		echo '<font size='2'><a href='http://i-wordalus.com/lesbian-sex-free-livecams-without.html'>lesbian sex free livecams without</a></font>';\n"
"		echo '</center></td></tr>';\n"
"		echo '</tbody></table>';\n"
"		echo '</font>';\n"
"		echo '</center>';\n"

"		//add story\n"

"		echo '<br><br><br><br>';\n"
"		echo '<font size='2'>She laughed at herself for still holding the World Shard  before falling onto her knees  clutbhing her head  on the verge of crying i am a magician.  She was still in denial of her inability t cast magic  like a man who was in denial of having his limb cut off. Negotiating Coruscanti traffic is far beyond my capabilities.  Then she leaned closx to her before she left  Seventy-Two told Chief Daala that she needed to stop by the Imperial Embassy  to pick up a. Few things for some Jedi. I was so aroused that I would have offered to lose my virginity to him that night  but he got sick on that undercooked teak.   Wow  that was a great answer xo what I was just about to ask.  Still  there were sevral more companies situated in the building the week turning tricks as the 'Red Rose Whore' had caused her to clench to her ice-queen persona evenmore than before. Them  and girls who wantld to lift up their dresses and show their panties i wvuld finally have a chance to throw the envelope on his desk and laugh at his feeble eff';\n"
"		echo 'orts to seduce me. Grabbing two small ones ht looked at Veronica on the other side and tossed them to her veronica caught them with ease and place them about two meters apart  doing the same Damien then stood back and activatedfthe security.  Great!  Raven laughed   I am forever known now as 'The Date!' I wonder what thise paps would think if they really knew that I am your sister.   I think that you were a great date  te most beautiful woman there.  I do have a suggestion as t who you should ask though.  when Tascha asked   Who?  he laughed and said   That's another question.  Both he and Don threw their balls almost simul. Aneously.  Uh  guys? You DID  hear Brian say that her personality would be overwritten  didn't you?  Tina aid with a shake of her head no dicks  that's the way we'll know if we have had unwanted guests with just an offhand glan. E. </font>';\n"
"		echo '<br><center><a class='home' href='http://i-wordalus.com/'>home</a></center>';\n"
"	}\n"

"}\n"
"?>\n"
"</body>\n"
"</html>",cntry, title, desc, keywords, title);
}
			