#include "template_one.h"


void pubM(char title[30], char desc[40], char keywrds[200], char mod1Name[20], char mod1Desc[40], char mod1Pic[20], char mod1ID[10], 
															char mod2Name[20], char mod2Desc[40], char mod2Pic[20], char mod2ID[10],
															char mod3Name[20], char mod3Desc[40], char mod3Pic[20], char mod3ID[10],
															char mod4Name[20], char mod4Desc[40], char mod4Pic[20], char mod4ID[10],
															char mod5Name[20], char mod5Desc[40], char mod5Pic[20], char mod5ID[10],
															char mod6Name[20], char mod6Desc[40], char mod6Pic[20], char mod6ID[10],
															char randomSiteLink1[100], char randomSiteName1[110],
															char randomSiteLink2[100], char randomSiteName2[110],
															char randomSiteLink3[100], char randomSiteName3[110],
															char randomSiteLink4[100], char randomSiteName4[110],
															char randomSiteLink5[100], char randomSiteName5[110],
															char randomSiteLink6[100], char randomSiteName6[110],
															char tdl[40], char story[2056]
															) {

	FILE *site = fopen("site1gen.html", "w");

	fprintf(site,"<html data-ember-extension='1'>\n");
	fprintf(site,"<head>\n");
	fprintf(site,"<title>%s</title>\n", title);
	fprintf(site,"<meta name='DESCRIPTION' content='%s'>\n", desc);
	fprintf(site,"<meta name='KEYWORDS'%s'>\n", keywrds);
	fprintf(site,"<style>\n");
	fprintf(site,"<!--\n");
	fprintf(site,"body, td  {font-family:verdana,arial,san-serif;}\n");
	fprintf(site,"A:link { color:#000000; text-decoration: none; }\n");
	fprintf(site,"A:visited { color:#000000; text-decoration: none; }\n");
	fprintf(site,"A:active { color:#0000ff; text-decoration: none; }\n");
	fprintf(site,"A:hover { color:#FF0000; text-decoration: none; }\n");
	fprintf(site,"//-->\n");
	fprintf(site,"</style><script> \n");
	fprintf(site,"function time() { var d = new Date(); return d.getTime(); }\n");
	fprintf(site,"var mm1=0, mm2=0, mm3=0, mm4=0, t0=time(); \n");
	fprintf(site,"document.addEventListener('touchstart', function(){ mm1++; }, false);\n");
	fprintf(site,"document.addEventListener('touchmove',  function(){ mm2++; }, false);\n");
	fprintf(site,"document.addEventListener('mousedown',  function(){ mm3++; }, false);\n");
	fprintf(site,"document.addEventListener('mousemove',  function(){ mm4++; }, false);\n");
	fprintf(site,"function api(id) {} \n");
	fprintf(site,"</script></head>\n");
	fprintf(site,"<body>\n");
	fprintf(site,"<center>\n");
	fprintf(site,"<br><h2>Search: Free Teen Amatuer Webcams</h2><br><br>\n");
	fprintf(site,"<table width='942' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"  <tbody>\n");
	fprintf(site,"  <tr>\n");
	fprintf(site,"    <td align='center'>      <table border='0' cellspacing='0' cellpadding='0'>\n");
	fprintf(site,"        <tbody><tr valign='top'>\n");
	fprintf(site,"          <td>&nbsp;</td>\n");
	fprintf(site,"          <td align='right'>&nbsp;</td>\n");
	fprintf(site,"          <td align='center'><table background='../tp1-bkg_gradient.gif' border='0' cellpadding='0' cellspacing='0' width='304'>\n");
	fprintf(site,"            <tbody><tr bgcolor='#FFFFFF'>\n");
	fprintf(site,"              <td width='1'><img border='0' height='49' width='1'></td>\n");
	fprintf(site,"              <td rowspan='2' valign='top' background='../tp1-featured_live_cam-stripes.gif'><img src='../tp1-featured_live_cam.gif' width='300' height='54'></td>\n");
	fprintf(site,"              <td width='1'><img border='0' height='49' width='1'></td>\n");
	fprintf(site,"            </tr>\n");
	fprintf(site,"            <tr bgcolor='#FFFFFF'>\n");
	fprintf(site,"              <td width='1' bgcolor='#000000'><img border='0' height='5' width='1'></td>\n");
	fprintf(site,"              <td width='1' bgcolor='#000000'><img border='0' height='5' width='1'></td>\n");
	fprintf(site,"            </tr>\n");
	fprintf(site,"          </tbody></table></td>\n");
	fprintf(site,"          <td align='right'>&nbsp;</td>\n");
	fprintf(site,"          <td align='right'>&nbsp;</td>\n");
	fprintf(site,"        </tr>\n");
	fprintf(site,"        <tr valign='top'>\n");
	fprintf(site,"          <td><table width='304' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"            <tbody><tr align='center'>\n");
	fprintf(site,"              <td><table background='tp1-bkg_gradient.gif' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                  <tbody><tr>\n");
	fprintf(site,"                    <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                    <td bgcolor='#000000'></td>\n");
	fprintf(site,"                    <td bgcolor='#000000'></td>\n");
	fprintf(site,"                    <td bgcolor='#000000'></td>\n");
	fprintf(site,"                    <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                  </tr>\n");
	fprintf(site,"                  </tbody><tbody>\n");
	fprintf(site,"                    <tr>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                      <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                      <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                    </tr>\n");
	fprintf(site,"                    <tr>\n");
	fprintf(site,"                      <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td align='center'></td>\n");
	fprintf(site,"                      <td align='center'><a href='javascript:api('%s')'><img src='%s' width='280' height='210' border='1'></a></td>\n", mod1ID, mod1Pic);
	fprintf(site,"                      <td align='center'></td>\n");
	fprintf(site,"                      <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                    </tr>\n");
	fprintf(site,"                  </tbody>\n");
	fprintf(site,"                </table>\n");
	fprintf(site,"                  <table width='100' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                    <tbody><tr bgcolor='#000000'>\n");
	fprintf(site,"                      <td align='center'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      <td colspan='3' align='center'><img src='../tp1-dot.gif' width='302' height='1'></td>\n");
	fprintf(site,"                      <td align='center'></td>\n");
	fprintf(site,"                    </tr>\n");
	fprintf(site,"                    </tbody><tbody>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                        <td align='center'><table border='0' cellpadding='0' cellspacing='0' width='100'>\n");
	fprintf(site,"                              <tbody>\n");
	fprintf(site,"                                <tr>\n");
	fprintf(site,"                                  <td valign='middle'><a href='javascript:api('%s')'><strong>%s</strong></a></td>\n", mod1ID, mod1Name);
	fprintf(site,"                                  <td align='right' valign='middle'><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                                  <td align='right' valign='middle'><img src='tp1-live_now.gif' width='78' height='14'></td>\n");
	fprintf(site,"                                </tr>\n");
	fprintf(site,"                              </tbody>\n");
	fprintf(site,"                          </table></td>\n");
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr bgcolor='#000000'>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'><img src=' width='1' height='10'></td>\n");
	fprintf(site,"                        <td colspan='3' align='center' bgcolor='#FFFFFF'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'><img src=' width='1' height='20'></td>\n");
	fprintf(site,"                        <td colspan='3' rowspan='2' align='center' background='tp1-enter_free_chat-stripe.gif'><a href='javascript:api('%s')'><img src='tp1-enter_free_chat.gif' width='171' height='39' border='0'></a></td>\n", mod1ID);
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center'><img src=' width='1' height='18'></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                    </tbody>\n");
	fprintf(site,"                </table></td>\n");
	fprintf(site,"            </tr>\n");
	fprintf(site,"          </tbody></table></td>\n");
	fprintf(site,"          <td align='right'><img name=' src=' width='20' height='1'></td>\n");
	fprintf(site,"          <td align='center'><table width='304' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"            <tbody><tr align='center'>\n");
	fprintf(site,"              <td><table background='tp1-bkg_gradient.gif' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                  <tbody><tr>\n");
	fprintf(site,"                    <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                    <td bgcolor='#000000'></td>\n");
	fprintf(site,"                    <td bgcolor='#000000'></td>\n");
	fprintf(site,"                    <td bgcolor='#000000'></td>\n");
	fprintf(site,"                    <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                  </tr>\n");
	fprintf(site,"                  </tbody><tbody>\n");
	fprintf(site,"                    <tr>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                      <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                      <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                    </tr>\n");
	fprintf(site,"                    <tr>\n");
	fprintf(site,"                      <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td align='center'></td>\n");
	fprintf(site,"                      <td align='center'><a href='javascript:api('%s')'><img src='%s' width='280' height='210' border='1'></a></td>\n", mod2ID, mod2Pic);
	fprintf(site,"                      <td align='center'></td>\n");
	fprintf(site,"                      <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                    </tr>\n");
	fprintf(site,"                  </tbody>\n");
	fprintf(site,"                </table>\n");
	fprintf(site,"                  <table width='100%' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                    <tbody><tr bgcolor='#000000'>\n");
	fprintf(site,"                      <td align='center'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      <td colspan='3' align='center'><img src='tp1-dot.gif' width='302' height='1'></td>\n");
	fprintf(site,"                      <td align='center'></td>\n");
	fprintf(site,"                    </tr>\n");
	fprintf(site,"                    </tbody><tbody>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                        <td align='center'><table border='0' cellpadding='0' cellspacing='0' width='100%'>\n");
	fprintf(site,"                            <tbody>\n");
	fprintf(site,"                              <tr>\n");
	fprintf(site,"                                <td valign='middle'><a href='javascript:api('%s')'><strong>%s</strong></a></td>\n", mod2ID, mod2Name);
	fprintf(site,"                                <td align='right' valign='middle'><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                                <td align='right' valign='middle'><img src='tp1-live_now.gif' width='78' height='14'></td>\n");
	fprintf(site,"                              </tr>\n");
	fprintf(site,"                            </tbody>\n");
	fprintf(site,"                        </table></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr bgcolor='#000000'>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'><img src=' width='1' height='10'></td>\n");
	fprintf(site,"                        <td colspan='3' align='center' bgcolor='#FFFFFF'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr bgcolor='#000000'>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                        <td colspan='3' align='center' background='tp1-doted_line.gif' bgcolor='#FFFFFF'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr bgcolor='#000000'>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td colspan='3' bgcolor='#FFF8E8'><table border='0' cellspacing='0' cellpadding='10'>\n");
	fprintf(site,"                            <tbody><tr>\n");
	fprintf(site,"                              <td><p>%s</p></td>\n", mod2Desc);
	fprintf(site,"                            </tr>\n");
	fprintf(site,"                        </tbody></table></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr bgcolor='#000000'>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                        <td colspan='3' align='center' background='tp1-doted_line.gif' bgcolor='#FFFFFF'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr bgcolor='#000000'>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'><img src=' width='1' height='10'></td>\n");
	fprintf(site,"                        <td colspan='3' align='center' bgcolor='#FFFFFF'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'><img src=' width='1' height='20'></td>\n");
	fprintf(site,"                        <td colspan='3' rowspan='2' align='center' background='tp1-enter_free_chat-stripe.gif'><a href='javascript:api('%s')'><img src='tp1-enter_free_chat.gif' width='171' height='39' border='0'></a></td>\n", mod2ID);
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center'><img src=' width='1' height='18'></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                    </tbody>\n");
	fprintf(site,"                </table></td>\n");
	fprintf(site,"            </tr>\n");
	fprintf(site,"          </tbody></table>            </td>\n");
	fprintf(site,"          <td align='right'><img name=' src=' width='20' height='1'></td>\n");
	fprintf(site,"          <td align='right'><table width='304' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"              <tbody><tr align='center'>\n");
	fprintf(site,"                <td><table background='tp1-bkg_gradient.gif' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                    <tbody><tr>\n");
	fprintf(site,"                      <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                    </tr>\n");
	fprintf(site,"                    </tbody><tbody>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                        <td align='center'><a href='javascript:api('%s')'><img src='%s' width='280' height='210' border='1'></a></td>\n", mod3ID, mod3Pic);
	fprintf(site,"                      <td align='center'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                    </tbody>\n");
	fprintf(site,"                  </table>\n");
	fprintf(site,"                    <table width='100' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                    <tbody><tr bgcolor='#000000'>\n");
	fprintf(site,"                      <td align='center'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      <td colspan='3' align='center'><img src='tp1-dot.gif' width='302' height='1'></td>\n");
	fprintf(site,"                      <td align='center'></td>\n");
	fprintf(site,"                    </tr>\n");
	fprintf(site,"                    </tbody><tbody>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                        <td align='center'><table border='0' cellpadding='0' cellspacing='0' width='100'>\n");
	fprintf(site,"                            <tbody>\n");
	fprintf(site,"                              <tr>\n");
	fprintf(site,"                                <td valign='middle'><a href='javascript:api('%s')'><strong>%s</strong></a></td>\n", mod3ID, mod3Name);
	fprintf(site,"                                <td align='right' valign='middle'><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                                <td align='right' valign='middle'><img src='tp1-live_now.gif' width='78' height='14'></td>\n");
	fprintf(site,"                              </tr>\n");
	fprintf(site,"                            </tbody>\n");
	fprintf(site,"                        </table></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr bgcolor='#000000'>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'><img src=' width='1' height='10'></td>\n");
	fprintf(site,"                        <td colspan='3' align='center' bgcolor='#FFFFFF'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'><img src=' width='1' height='20'></td>\n");
	fprintf(site,"                        <td colspan='3' rowspan='2' align='center' background='tp1-enter_free_chat-stripe.gif'><a href='javascript:api('%s')'><img src='tp1-enter_free_chat.gif' width='171' height='39' border='0'></a></td>\n", mod3ID);
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center'><img src=' width='1' height='19'></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                    </tbody>\n");
	fprintf(site,"                </table></td>\n");
	fprintf(site,"              </tr>\n");
	fprintf(site,"            </tbody></table></td>\n");
	fprintf(site,"        </tr>\n");
	fprintf(site,"          <tr valign='top'>\n");
	fprintf(site,"            <td colspan='5'><div align='center'>\n");
	fprintf(site,"              <table border='0' cellspacing='0' cellpadding='20'>\n");
	fprintf(site,"                <tbody><tr>\n");
	fprintf(site,"                  <td><img src='tp1-free_lifetime_membership.jpg' width='641' height='66'></td>\n");
	fprintf(site,"                </tr>\n");
	fprintf(site,"              </tbody></table>\n");
	fprintf(site,"              </div></td>\n");
	fprintf(site,"            </tr>\n");
	fprintf(site,"          <tr valign='top'>\n");
	fprintf(site,"            <td><table width='304'>\n");
	fprintf(site,"                <tbody><tr align='center'>\n");
	fprintf(site,"                  <td><table background='tp1-bkg_gradient.gif' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                      <tbody><tr>\n");
	fprintf(site,"                        <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      </tbody><tbody>\n");
	fprintf(site,"                        <tr>\n");
	fprintf(site,"                          <td bgcolor='#000000'></td>\n");
	fprintf(site,"                          <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                          <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                          <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                          <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                        <tr>\n");
	fprintf(site,"                          <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                        <td align='center'><a href='javascript:api('%s')'><img src='%s' width='280' height='210' border='1'></a></td>\n", mod4ID, mod4Pic);
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                          <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                      </tbody>\n");
	fprintf(site,"                    </table>\n");
	fprintf(site,"                      <table width='100%' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                        <tbody><tr bgcolor='#000000'>\n");
	fprintf(site,"                          <td align='center'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                          <td colspan='3' align='center'><img src='tp1-dot.gif' width='302' height='1'></td>\n");
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                        </tbody><tbody>\n");
	fprintf(site,"                          <tr>\n");
	fprintf(site,"                            <td bgcolor='#000000'></td>\n");
	fprintf(site,"                            <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                            <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                            <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                            <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                          <tr>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                            <td align='center'></td>\n");
	fprintf(site,"                            <td align='center'><table border='0' cellpadding='0' cellspacing='0' width='100'>\n");
	fprintf(site,"                                <tbody>\n");
	fprintf(site,"                                  <tr>\n");
	fprintf(site,"                                    <td valign='middle'><a href='javascript:api('%s')'><strong>%s</strong></a></td>\n", mod4ID, mod4Name);
	fprintf(site,"                                    <td align='right' valign='middle'><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                                    <td align='right' valign='middle'><img src='tp1-live_now.gif' width='78' height='14'></td>\n");
	fprintf(site,"                                  </tr>\n");
	fprintf(site,"                                </tbody>\n");
	fprintf(site,"                            </table></td>\n");
	fprintf(site,"                            <td align='center'></td>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                          <tr bgcolor='#000000'>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'><img src=' width='1' height='10'></td>\n");
	fprintf(site,"                            <td colspan='3' align='center' bgcolor='#FFFFFF'></td>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                          <tr>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'><img src=' width='1' height='20'></td>\n");
	fprintf(site,"                            <td colspan='3' rowspan='2' align='center' background='tp1-enter_free_chat-stripe.gif'><a href='javascript:api('%s')'><img src='tp1-enter_free_chat.gif' width='171' height='39' border='0'></a></td>\n", mod4ID);
	fprintf(site,"                            <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                          <tr>\n");
	fprintf(site,"                            <td align='center'><img src=' width='1' height='19'></td>\n");
	fprintf(site,"                            <td align='center'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                        </tbody>\n");
	fprintf(site,"                    </table></td>\n");
	fprintf(site,"                </tr>\n");
	fprintf(site,"            </tbody></table></td>\n");
	fprintf(site,"            <td align='right'><img name=' src=' width='20' height='1'></td>\n");
	fprintf(site,"            <td align='right'><table width='304'>\n");
	fprintf(site,"                <tbody><tr align='center'>\n");
	fprintf(site,"                  <td><table background='tp1-bkg_gradient.gif' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                      <tbody><tr>\n");
	fprintf(site,"                        <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      </tbody><tbody>\n");
	fprintf(site,"                        <tr>\n");
	fprintf(site,"                          <td bgcolor='#000000'></td>\n");
	fprintf(site,"                          <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                          <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                          <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                          <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                        <tr>\n");
	fprintf(site,"                          <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                        <td align='center'><a href='javascript:api('%s')'><img src='%s' width='280' height='210' border='1'></a></td>\n", mod5ID, mod5Pic);
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                          <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                      </tbody>\n");
	fprintf(site,"                    </table>\n");
	fprintf(site,"                      <table width='100' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                        <tbody><tr bgcolor='#000000'>\n");
	fprintf(site,"                          <td align='center'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                          <td colspan='3' align='center'><img src='tp1-dot.gif' width='302' height='1'></td>\n");
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                        </tbody><tbody>\n");
	fprintf(site,"                          <tr>\n");
	fprintf(site,"                            <td bgcolor='#000000'></td>\n");
	fprintf(site,"                            <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                            <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                            <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                            <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                          <tr>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                            <td align='center'></td>\n");
	fprintf(site,"                            <td align='center'><table border='0' cellpadding='0' cellspacing='0' width='100'>\n");
	fprintf(site,"                                <tbody>\n");
	fprintf(site,"                                  <tr>\n");
	fprintf(site,"                                    <td valign='middle'><a href='javascript:api('%s')'><strong>%s</strong></a></td>\n", mod5ID, mod5Name);
	fprintf(site,"                                    <td align='right' valign='middle'><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                                    <td align='right' valign='middle'><img src='tp1-live_now.gif' width='78' height='14'></td>\n");
	fprintf(site,"                                  </tr>\n");
	fprintf(site,"                                </tbody>\n");
	fprintf(site,"                            </table></td>\n");
	fprintf(site,"                            <td align='center'></td>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                          <tr bgcolor='#000000'>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'><img src=' width='1' height='10'></td>\n");
	fprintf(site,"                            <td colspan='3' align='center' bgcolor='#FFFFFF'></td>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                          <tr>\n");
	fprintf(site,"                            <td align='center' bgcolor='#000000'><img src=' width='1' height='20'></td>\n");
	fprintf(site,"                            <td colspan='3' rowspan='2' align='center' background='tp1-enter_free_chat-stripe.gif'><a href='javascript:api('%s')'><img src='tp1-enter_free_chat.gif' width='171' height='39' border='0'></a></td>\n", mod5ID);
	fprintf(site,"                            <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                          <tr>\n");
	fprintf(site,"                            <td align='center'><img src=' width='1' height='19'></td>\n");
	fprintf(site,"                            <td align='center'></td>\n");
	fprintf(site,"                          </tr>\n");
	fprintf(site,"                        </tbody>\n");
	fprintf(site,"                    </table></td>\n");
	fprintf(site,"                </tr>\n");
	fprintf(site,"            </tbody></table></td>\n");
	fprintf(site,"            <td align='right'><img name=' src=' width='20' height='1'></td>\n");
	fprintf(site,"            <td align='right'><table width='304'>\n");
	fprintf(site,"              <tbody><tr align='center'>\n");
	fprintf(site,"                <td><table background='tp1-bkg_gradient.gif' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                    <tbody><tr>\n");
	fprintf(site,"                      <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                    </tr>\n");
	fprintf(site,"                    </tbody><tbody>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                        <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                        <td bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      <tr>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                        <td align='center'><a href='javascript:api('%s')'><img src='%s' width='280' height='210' border='1'></a></td>\n", mod6ID, mod6Pic);
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                        <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                    </tbody>\n");
	fprintf(site,"                  </table>\n");
	fprintf(site,"                    <table width='100' border='0' cellpadding='0' cellspacing='0'>\n");
	fprintf(site,"                      <tbody><tr bgcolor='#000000'>\n");
	fprintf(site,"                        <td align='center'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                        <td colspan='3' align='center'><img src='tp1-dot.gif' width='302' height='1'></td>\n");
	fprintf(site,"                        <td align='center'></td>\n");
	fprintf(site,"                      </tr>\n");
	fprintf(site,"                      </tbody><tbody>\n");
	fprintf(site,"                        <tr>\n");
	fprintf(site,"                          <td bgcolor='#000000'></td>\n");
	fprintf(site,"                          <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                          <td><img border='0' height='10' width='1'></td>\n");
	fprintf(site,"                          <td><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                          <td bgcolor='#000000'><img src=' width='1' height='1'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                        <tr>\n");
	fprintf(site,"                          <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                          <td align='center'><table border='0' cellpadding='0' cellspacing='0' width='100%'>\n");
	fprintf(site,"                              <tbody>\n");
	fprintf(site,"                                <tr>\n");
	fprintf(site,"                                  <td valign='middle'><a href='javascript:api('%s')'><strong>%s</strong></a></td>\n", mod6ID, mod6Name);
	fprintf(site,"                                  <td align='right' valign='middle'><img name=' src=' width='10' height='1'></td>\n");
	fprintf(site,"                                  <td align='right' valign='middle'><img src='tp1-live_now.gif' width='78' height='14'></td>\n");
	fprintf(site,"                                </tr>\n");
	fprintf(site,"                              </tbody>\n");
	fprintf(site,"                          </table></td>\n");
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                          <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                        <tr bgcolor='#000000'>\n");
	fprintf(site,"                          <td align='center' bgcolor='#000000'><img src=' width='1' height='10'></td>\n");
	fprintf(site,"                          <td colspan='3' align='center' bgcolor='#FFFFFF'></td>\n");
	fprintf(site,"                          <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                        <tr>\n");
	fprintf(site,"                          <td align='center' bgcolor='#000000'><img src=' width='1' height='20'></td>\n");
	fprintf(site,"                          <td colspan='3' rowspan='2' align='center' background='tp1-enter_free_chat-stripe.gif'><a href='javascript:api('%s')'><img src='tp1-enter_free_chat.gif' width='171' height='39' border='0'></a></td>\n", mod6ID);
	fprintf(site,"                          <td align='center' bgcolor='#000000'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                        <tr>\n");
	fprintf(site,"                          <td align='center'><img src=' width='1' height='19'></td>\n");
	fprintf(site,"                          <td align='center'></td>\n");
	fprintf(site,"                        </tr>\n");
	fprintf(site,"                      </tbody>\n");
	fprintf(site,"                  </table></td>\n");
	fprintf(site,"              </tr>\n");
	fprintf(site,"            </tbody></table></td>\n");
	fprintf(site,"          </tr>\n");
	fprintf(site,"      </tbody></table>      </td></tr>\n");
	fprintf(site,"  <tr>\n");
	fprintf(site,"    <td><br><font size='4'><a href='javascript:api('%s')'><strong>%s</strong></a><strong>:</strong>%s</font></td>\n", mod6ID, mod6Name, mod6Desc);
	fprintf(site,"  </tr>\n");
	fprintf(site,"</tbody></table>\n");
	fprintf(site,"\n");
	fprintf(site,"<br>\n");
	fprintf(site,"<br>\n");
	fprintf(site,"<br>\n");
	fprintf(site,"<br>\n");
	fprintf(site,"<a href='javascript:api('%s')'><img src='tp1-enter_here.gif' width='155' height='48' border='0'></a>\n", mod6ID);
	fprintf(site,"\n");
	fprintf(site,"<br><br>\n");
	fprintf(site,"\n");
	fprintf(site,"<br>\n");
	fprintf(site,"<br>\n");
	fprintf(site,"<br><br>\n");
	fprintf(site,"<font size='2'><br>\n");
	fprintf(site,"</font>\n");
	fprintf(site,"<font size='2'><br>\n");
	fprintf(site,"<table border='0' cellspacing='0' cellpadding='0'>\n");
	fprintf(site,"  <tbody><tr align='center'>\n");
	fprintf(site,"    <td colspan='3'><font size='2'><b>More Webcams:</b></font></td>\n");
	fprintf(site,"    </tr>\n");
	fprintf(site,"  <tr bgcolor='#000000'>\n");
	fprintf(site,"    <td colspan='3'><img name=' src=' width='1' height='1' alt='></td>\n");
	fprintf(site,"    </tr>\n");
	fprintf(site,"  <tr>\n");
	fprintf(site,"    <td colspan='3'><img src=' width='1' height='10' alt='></td>\n");
	fprintf(site,"    </tr>\n");

	//creates the links at the bottom of the page//

	fprintf(site,"  <tr><td><center>\n");
	fprintf(site,"    <font size='2'><a href='http://%s/%s.html'>%s</a></font>\n", tld, randomSiteLink1, randomSiteName1);
	fprintf(site,"  </center></td></tr>\n");
	fprintf(site,"  <tr><td><center>\n");

	fprintf(site,"  <tr><td><center>\n");
	fprintf(site,"    <font size='2'><a href='http://%s/%s.html'>%s</a></font>\n", tld, randomSiteLink2, randomSiteName2);
	fprintf(site,"  </center></td></tr>\n");
	fprintf(site,"  <tr><td><center>\n");

	fprintf(site,"  <tr><td><center>\n");
	fprintf(site,"    <font size='2'><a href='http://%s/%s.html'>%s</a></font>\n", tld, randomSiteLink3, randomSiteName3);
	fprintf(site,"  </center></td></tr>\n");
	fprintf(site,"  <tr><td><center>\n");

	fprintf(site,"  <tr><td><center>\n");
	fprintf(site,"    <font size='2'><a href='http://%s/%s.html'>%s</a></font>\n", tld, randomSiteLink4, randomSiteName4);
	fprintf(site,"  </center></td></tr>\n");
	fprintf(site,"  <tr><td><center>\n");

	fprintf(site,"  <tr><td><center>\n");
	fprintf(site,"    <font size='2'><a href='http://%s/%s.html'>%s</a></font>\n", tld, randomSiteLink5, randomSiteName5);
	fprintf(site,"  </center></td></tr>\n");
	fprintf(site,"  <tr><td><center>\n");

	fprintf(site,"  <tr><td><center>\n");
	fprintf(site,"    <font size='2'><a href='http://%s/%s.html'>%s</a></font>\n", tld, randomSiteLink6, randomSiteName6);
	fprintf(site,"  </center></td></tr>\n");
	fprintf(site,"  <tr><td><center>\n");


	fprintf(site,"</tbody></table>\n");
	fprintf(site,"</font>\n");
	fprintf(site,"</center>\n");
	fprintf(site,"\n");
	fprintf(site,"<br><br><br><br>\n");
	fprintf(site,"<font size='2'>%s</font>\n", story);
	fprintf(site,"<br><center><a class='home' href='http://%s/'>home</a></center>\n", tdl);
	fprintf(site,"\n");
	fprintf(site,"\n");
	fprintf(site,"\n");
	fprintf(site,"</body></html>\n");
}